name: kongkon
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  page_transition: ^2.1.0
  provider: ^6.1.2
  material_symbols_icons: ^4.2789.0
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  flutter_secure_storage: ^9.2.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - assets/merchant/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf

 